### ISSUE TITLE
DATA ASSSENZE,RITARDI,USCITE ED EVENTUALI

### ISSUE THREAD

**Issue by sempliciniluigi89** [Giua-app/Giua-App#102]
Buonasera,sarebbe possibile far vedere la data delle assenze,ritardi e uscite?grazie  Inoltre sarebbe possibile diminuire il carattere dei nomi delle materie nella sezioni lezioni in quanto l'app spezza e va a capo per certe materie come ad esempio MATEMATICA?grazie 
Inoltre sarebbe bello evidenziare di colori diversi le assenze giustificate da quelle non giustificate,stessa cosa per i ritardi e per le uscite

**Comment by Franck1421** [comment]
Le sue richieste riguardanti le assenze e le giustificazioni sono già state implementate nell'app già da varie versioni. Per quanto riguarda la sezione lezioni avevamo già in programma di modificare l'interfaccia ma questo avverrà in future release.
