### ISSUE TITLE
L'app non fa vedere l'attività descritta nella sezione Sostegno

### ISSUE THREAD

**Issue by sempliciniluigi89** [Giua-app/Giua-App#106]
Buongiorno, ho provato ad accedere come genitore di un alunno con bes (bisogni educati speciale) e devo dire che entrando nell'app giua , nella sezione lezioni , risulta la materia sostegno ,ma quando si clicca sopra , dice argomenti e attività non specificata, quando invece accedendo online risulta il tutto

**Comment by Franck1421** [comment]
Può mandare uno screenshot della schermata del registro online dove è presente questa lezione?

**Comment by sempliciniluigi89** [comment]
Questo è quanto risulta nel registro online e che non risulta nell'app 

https://user-images.githubusercontent.com/93823125/151417458-30e5a0e9-e2c7-4391-872c-764c679bc251.png

**Comment by Franck1421** [comment]
Effetivamente nelle lezioni di sostegno non ci sono argomenti e attività per quello l'app non le mostra. Il problema è che l'app non sa prendere l'informazione dalla sezione "Sostegno". Il problema verrà risolto nella prossima release
