### ISSUE TITLE
Problema secondo quadrimestre

### ISSUE THREAD

**Issue by sempliciniluigi89** [Giua-app/Giua-App#107]
Buongiorno ,avendo chiuso il primo quadrimestre e iniziato il secondo ,oggi ho inserito dei voti agli alunni , i quali mi hanno comunicato che con l'app giua il voto risulta colorato di verde ,ma nella cella medie risulta il seguente segno / , il che significa che non fa media.Io poi ho controllato di averlo inserito come voto facente media, effettivamente è un problema dell'app

**Comment by HiemSword** [comment]
Bug confermato, verrà risolto nella prossima release. Comunque volevo informarla che è possibile segnalare bug anche da dentro l'app per le persone senza account GitHub
