### ISSUE TITLE
Agenda non funziona

### ISSUE THREAD

**Issue by sempliciniluigi89** [Giua-app/Giua-App#108]
Inoltre appena si cerca di fare accesso all'agenda ,l'app non funzione e fa uscire

**Comment by Franck1421** [comment]
Se intende che l' app va nella schermata di crash (quella con l'immagine della chiocciola o del registro al centro) potrebbe inviarci l'errore andando in dettagli e poi cliccando copia in basso a sinistra?

**Comment by sempliciniluigi89** [comment]
Build version: 0.6.3-stable 
Build date: 15-01-2022 17:54:28 
Current date: 01-02-2022 23:37:35 
Device: Samsung SM-A505FN 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.ArrayIndexOutOfBoundsException: length=1; index=2
	at com.giua.pages.AgendaPage.getAllAgendaObjectsWithoutDetails(AgendaPage.java:29)
	at com.giua.app.ui.fragments.agenda.AgendaFragment$$ExternalSyntheticLambda1.run(Unknown Source:29)
	at java.lang.Thread.run(Thread.java:923)

User actions: 
2022-02-01 23:36:58: AutomaticLoginActivity created
2022-02-01 23:36:58: AutomaticLoginActivity resumed
2022-02-01 23:36:58: ActivityManager destroyed
2022-02-01 23:37:00: AutomaticLoginActivity paused
2022-02-01 23:37:00: DrawerActivity created
2022-02-01 23:37:00: DrawerActivity resumed
2022-02-01 23:37:01: AutomaticLoginActivity destroyed

**Comment by Franck1421** [comment]
Non riesco a replicare l'errore. Potrebbe inviare una foto dell'agenda del registro del mese di gennaio e febbraio?

**Comment by sempliciniluigi89** [comment]
Potrebbe essere più esplicito?Intende l'agenda presente nell'app o nel registro online ?

**Comment by Franck1421** [comment]
Intendo il registro online

**Comment by sempliciniluigi89** [comment]
Lato genitore giusto?

**Comment by sempliciniluigi89** [comment]
https://user-images.githubusercontent.com/93823125/152653036-aeb04164-7ba8-4be1-9e40-bb3630ad3fac.JPG

https://user-images.githubusercontent.com/93823125/152653038-5ed28f7c-9bd6-4d76-9f2c-569a02fa7de1.JPG

**Comment by Franck1421** [comment]
Mi potrebbe dire se questo errore si verifica ogni volta che si accede all'agenda dell'app oppure se capita solo qualche volta?

**Comment by sempliciniluigi89** [comment]
Il problema si presenta ogni qualvolta si clicchi sull'agenda

Il Dom 6 Feb 2022, 16:28 Franck1421 ***@***.***> ha scritto:

**Comment by Franck1421** [comment]
Abbiamo trovato l'errore, verrà risolto nella prossima release.

**Comment by sempliciniluigi89** [comment]
Buonasera ,so che è difficile rispondere a questa domanda,ma numerosi
genitori ci chiedono informazioni in merito alla data dell'uscita della
nuova versione in quanto vi sono numerosi problemi che non permettono il
regolare funzionamento della stessa app

Il Dom 6 Feb 2022, 16:46 Franck1421 ***@***.***> ha scritto:

**Comment by Franck1421** [comment]
Le posso dire che la release uscirà a breve includendo la risoluzione di questo problema, ma non di quello delle lezioni di sostegno (https://github.com/Giua-app/Giua-App/issues/106)

**Comment by sempliciniluigi89** [comment]
Sì, per il problema del sostegno si può anche aspettare ,non è urgentissimo
ecco

Il Dom 6 Feb 2022, 17:02 Franck1421 ***@***.***> ha scritto:
