### ISSUE TITLE
Bug URL 

### ISSUE THREAD

**Issue by gmontalbano5ct** [Giua-app/Giua-App#110]
Non mi fa accedere al registro dall app perché il mio URL finisce con / ma non lo fa inserire come faccio a farlo funzionare?

**Comment by Franck1421** [comment]
Ha provato a non inserire lo / finale e ad inserire il resto dell'url? Per esempio se il suo URL normale è "http://example.com/" inserisca "http://example.com" (senza le virgolette)

**Comment by gmontalbano5ct** [comment]
Appena non metto / finale provo ad accedere mi dice c'è un errore sconosciuto

**Comment by gmontalbano5ct** [comment]
@Franck1421

**Comment by HiemSword** [comment]
Puo mandarci uno screenshot del LogDog? (accessibile abilitando la modalità debug nelle impostazioni e cliccando su "Mostra LogDog) Se i log contengono informazioni personali e non vuole pubblicarle qua su github, ci contatti all'indirizzo email contact@appgiua.slmail.me

**Comment by gmontalbano5ct** [comment]
Mi scusi cos'è il log dove @HiemSword

**Comment by gmontalbano5ct** [comment]
Qual è?

**Comment by HiemSword** [comment]
> Mi scusi cos'è il log dove @HiemSword

Deve andare sulle Impostazioni e poi abilitare la modalità Debug, in fondo comparirà la sezione "Debug" e deve cliccare "Mostra LogDog". Dovrebbe aprirsi una nuova schermata con tante scritte, deve fare la foto alle scritte in rosso più recenti (vedere la data affianco ad ogni scritta).

**Comment by gmontalbano5ct** [comment]
![Screenshot_2022-02-07-12-09-41-733_com giua app](https://user-images.githubusercontent.com/93207960/152777308-60c3474f-1de5-4f18-8980-2d59e6a83cdb.jpg)
![Screenshot_2022-02-07-12-10-16-960_com giua app](https://user-images.githubusercontent.com/93207960/152777368-ea641955-bd66-43bd-9bd7-02bbd109ee35.jpg)
@HiemSword

**Comment by Franck1421** [comment]
Potrebbe inviare anche l'immagine della parte che sta più sotto della scritta rossa? Inoltre le sconsiglio l'utilizzo della modalità demo in quanto presenta numerosi errori.

**Comment by gmontalbano5ct** [comment]
![Screenshot_2022-02-07-13-01-10-676_com giua app](https://user-images.githubusercontent.com/93207960/152784478-d6f4a569-ff25-4372-b0c0-477dd9a72bc0.jpg)
![Screenshot_2022-02-07-12-59-57-881_com giua app](https://user-images.githubusercontent.com/93207960/152784489-9c7adf3b-e165-46bb-b4e2-6501140f825d.jpg)
@HiemSword

**Comment by gmontalbano5ct** [comment]
@HiemSword mi sa aiutare ?

**Comment by HiemSword** [comment]
È sicuro di aver inserito lo stesso url che usa sul proprio browser per andare nella pagina principale del registro?

**Comment by HiemSword** [comment]
Chiudo questa issue per inattività
