### ISSUE TITLE
App Richiesta Per Docenti

### ISSUE THREAD

**Issue by manuelbarberi** [Giua-app/Giua-App#112]
Sarebbe possibile realizzare un app per docenti?

**Comment by HiemSword** [comment]
Purtroppo no perchè non abbiamo sostegno economico/strutturale/organizzativo di nessun tipo da parte del nostro istituto e neanche da altri. 
Adattare l'app anche per i docenti è un lavoro troppo grande che richiederebbe parte (se non tutto) del nostro tempo libero che usiamo già per sviluppare l'app per gli studenti. Se ritiene indispensabile questa funzionalità può contattarci via email a contact@appgiua.slmail.me per discuterne dal punto di vista economico
