### ISSUE TITLE
VIsualizzazione voti

### ISSUE THREAD

**Issue by sempliciniluigi89** [Giua-app/Giua-App#127]
Buonasera ,so che vi chiedo troppo ,ma sarebbe possibile cambiare la grafica dei voti ? Allego foto di quello che intendo ,so che richiede tempo ,ma sarebbe bello vedere il tutto organizzato in questo modo anziché i voti in un quadratino o rettangolino 
https://user-images.githubusercontent.com/93823125/155599243-da0fda25-30b4-477b-b760-09b2dfa9482b.jpg
https://user-images.githubusercontent.com/93823125/155599440-dcbc2bcf-b1b4-42de-a591-7dbf0ae16a8e.jpg

**Comment by sempliciniluigi89** [comment]
La richiesta di cambiare la grafica dei voti non è casuale, in quanto abbiamo testato che inserendo più valutazioni a un alunno il genitore non se ne accorge della presenza di queste in quanto sono numerose e per vederle deve trascinare con il dito da destra a sinistra ,invece impostando la grafica mandata del registro classeviva ,si ha una completa visuale delle valutazioni con   data e tipologia ed eventuale commento/descrizione subito visibile

**Comment by HiemSword** [comment]
Prenderemo in considerazione la proposta ma ovviamente non posso assicurarle che verrà implementata nella prossima versione
