### ISSUE TITLE
Richiesta lezioni e segnlazione problema notifiche

### ISSUE THREAD

**Issue by Faobi69** [Giua-app/Giua-App#137]
Buona sera, volevo chiedervi se è possibile modificare la parte "Lezioni svolte" con una più simile a questa, in modo da ritrovare nella giornata di oggi e in quelle precedenti tutte le lezioni fatte (cosa già presente) ma nella parte superiore gli eventuali voti (con i relativi colori, tipologia, giudio) e le eventuali note disciplinari e/o osservazioni inserite in quella giornata per quel determinato alunno, troverei molto utile questa aggiunta personalmente, grazie

Inoltre volevo informarvi che, nonostante le notifiche siano attive, quando vengono inseriti nuovi voti/comunicazioni non compaiono le notifiche sul cellulare.

**Comment by HiemSword** [comment]
> volevo chiedervi se è possibile modificare la parte "Lezioni svolte" con una più simile a questa

Non capisco cosa intende con "questa", per caso voleva caricare un immagine? In ogni caso, in questo momento ci stiamo concentrando a risolvere i bug dell'app e le funzionalità mancanti ma prenderemo in considerazione la sua proposta nel futuro.

> Inoltre volevo informarvi che, nonostante le notifiche siano attive, quando vengono inseriti nuovi voti/comunicazioni non compaiono le notifiche sul cellulare.

Le notifiche possono impiegarci un pò ad arrivare (circa 1 ora da quando viene effetivamente inserita la comunicazione). Le consiglio di controllare, attraverso l'intro (accessibile nelle Impostazioni -> Rivedi l'intro), di aver disattivato il Risparmio Batteria e di aver consentito all'app di avviarsi all'avvio (se non si vuole dare questo permesso all'app, allora bisognerà manualmente avviare l'app ogni volta che si accende il telefono per attivare le notifiche)

**Comment by Faobi69** [comment]
![Capture](https://user-images.githubusercontent.com/73667418/162501112-663c493b-bd42-4868-a419-f8209020bd6c.PNG)
grazie mille, si volevo caricare questa immagine, poi altre due cose, ho notato, ma non vorrei dire una cosa per un'altra, che la materia religione è inclusa nella media totale della home page anche se non dovrebbe essere considerata e volevo anche chiedere se nella prossima versione rilascerete anche la parte per le note disciplinare con le eventuali notifiche.

**Comment by sempliciniluigi89** [comment]
> Buona sera, volevo chiedervi se è possibile modificare la parte "Lezioni svolte" con una più simile a questa, in modo da ritrovare nella giornata di oggi e in quelle precedenti tutte le lezioni fatte (cosa già presente) ma nella parte superiore gli eventuali voti (con i relativi colori, tipologia, giudio) e le eventuali note disciplinari e/o osservazioni inserite in quella giornata per quel determinato alunno, troverei molto utile questa aggiunta personalmente, grazie
> 
> Inoltre volevo informarvi che, nonostante le notifiche siano attive, quando vengono inseriti nuovi voti/comunicazioni non compaiono le notifiche sul cellulare.

Ottima proposta

**Comment by Franck1421** [comment]
> volevo anche chiedere se nella prossima versione rilascerete anche la parte per le note disciplinare con le eventuali notifiche.

Abbiamo in programma altre funzionalità, ma non escludo la possibilità che vengano aggiunte nella prossima release.
