### ISSUE TITLE
VOTI NON MEDIA E MATERIA RELIGIONE

### ISSUE THREAD

**Issue by Faobi69** [Giua-app/Giua-App#138]
Buon giorno, scusate il giorno in cui pubblico l'errore ma almeno lo vedete il prima possibile, i voti della materia religione fanno media nell'app anche se non dovrebbero farla essendo una materia opzionale che non tutti gli studenti fanno, (inoltre nella creazione della materia è stato messo che non deve fare media negli scrutini).

Un'altro problema sono i singoli voti che non dovrebbero fare media nelle singole materie, inserendo un 10 o qualsiasi voto in una qualsiasi materia e decidendo che questo non valga per la media, l'app lo visualizza in verde o rosso e lo considera per la media.

**Comment by Franck1421** [comment]
> Buon giorno, scusate il giorno in cui pubblico l'errore ma almeno lo vedete il prima possibile, i voti della materia religione fanno media nell'app anche se non dovrebbero farla essendo una materia opzionale che non tutti gli studenti fanno, (inoltre nella creazione della materia è stato messo che non deve fare media negli scrutini).

Verranno esclusi dalla media nella prossima release.

> Un'altro problema sono i singoli voti che non dovrebbero fare media nelle singole materie, inserendo un 10 o qualsiasi voto in una qualsiasi materia e decidendo che questo non valga per la media, l'app lo visualizza in verde o rosso e lo considera per la media.

È sicuro di aver messo il voto come non valido per la media? Abbiamo testato questa funzionalità e non ci risulta il problema.

**Comment by HiemSword** [comment]
Chiudo per inattività
