### ISSUE TITLE
PROBLEMA DIVISIONE VALUTAZIONI PER PERIODO

### ISSUE THREAD

**Issue by gmontalbano5ct** [Giua-app/Giua-App#142]
Non divide le valutazione esempio 1 trimestre 2 trimestre scrutinio finale perché?
![Screenshot_2022-04-27-14-14-48-606_com giua app](https://user-images.githubusercontent.com/93207960/165515828-059d7cd1-0629-49df-ba11-fe2ab1d2a15d.jpg)
@Franck1421 @HiemSword @Krek3r 
Potete risolvere perché non sono tutte le scuole ad avere il quadrimestre?

**Comment by Franck1421** [comment]
Può mandare una foto della pagina dei voti presa dal registro online?

**Comment by gmontalbano5ct** [comment]
![IMG_20220427_151944](https://user-images.githubusercontent.com/93207960/165527216-b3e1b6f2-8f53-40b4-baf6-655cf79c7c0d.jpg)
@Franck1421 c'è anche la possibilità di mettere tutte le materie

**Comment by gmontalbano5ct** [comment]
@Franck1421 è riuscito a capire il problema?

**Comment by gmontalbano5ct** [comment]
mi faccia sapere grazie buon lavoro

**Comment by gmontalbano5ct** [comment]
@Franck1421 è riuscito a trovare una soluzione?

**Comment by Franck1421** [comment]
Risolto nella 0.7.0
