### ISSUE TITLE
Accesso come Docente

### ISSUE THREAD

**Issue by Forrest-It** [Giua-app/Giua-App#174]
**Descrizione del bug**
Salve, non sono sicuro che si tratta di un bug: ho provato ad accedere con l'app utilizzando un account di docente ( sto testando giua@school per la scuola di mia figlia ) e ricevo un errore generico. E' una limitazione o un bug ?

**Indica i passaggi per riprodurre il bug**
dopo l'inserimento dei dato di accesso si verifca un errore generico 

**Informazioni Dispositivo**
Versione App:  0.7.1
Versione Android: 10
Modello dispositivo: Galaxy A7

Grazie

Tommaso

**Comment by Franck1421** [comment]
Vedere #112
