### ISSUE TITLE
Idea app docenti

### ISSUE THREAD

**Issue by manuelbarberi** [Giua-app/Giua-App#181]
Sarebbe possibile creare un'app per docenti?

**Comment by HiemSword** [comment]
No perchè, come le abbiamo già spiegato più volte nella issue #112 e #154, adattare l'app anche per i docenti o crearne una nuova è un lavoro troppo impegnativo che richiederebbe parte (se non tutto) del nostro tempo libero che usiamo già per sviluppare l'app per gli studenti. Se lei o la sua scuola ritiene indispensabile questa funzionalità può contattarci via email a contact@appgiua.slmail.me per discutere di un eventuale compenso per la sua implementazione
