### ISSUE TITLE
Giustifica Uscita anticipata e altri problemi

### ISSUE THREAD

**Issue by sempliciniluigi89** [Giua-app/Giua-App#182]
Buonasera, circa una settimana fa è stato rilasciato l'aggiornamento del registro Giua@school con l'implementazione della giustifica anche dell'uscita anticipata che prima non era prevista .Per tanto tentando di giustificare dall'app ,non giustifica affatto l'uscita anticipata ,cosa contraria all'assenza o al ritardo che giustifica perfettamente .Ripeto è un'implementazione del tutto nuova ,ed è sicuramente per questo che non funziona.Detto questo torno a lamentarmi sul fatto delle notifiche che non è che arrivano con 1 ora di ritardo, magari fosse così , invece no ,delle volte non arrivano proprio o arrivano dopo 3/4 ore .Come è possibile che l'app del registro opensource LAMPSchool faceva comparire la notifica nello stesso momento in cui si pubblicava qualcosa?Inoltre l'unica notifica che da dopo 3/4 ore è solo in merito alle valutazioni ,mentre ,per quanto riguarda le circolari ,i compiti ,programmazione delle verifiche non dà niente.

**Comment by HiemSword** [comment]
> circa una settimana fa è stato rilasciato l'aggiornamento del registro Giua@school con l'implementazione della giustifica anche dell'uscita anticipata che prima non era prevista .Per tanto tentando di giustificare dall'app ,non giustifica affatto l'uscita anticipata ,cosa contraria all'assenza o al ritardo che giustifica perfettamente

Le ricordiamo che l'app in questo momento riceve solo aggiornamenti di manutenzione, questo significa che non verranno implementate nuove funzionalità ma solo risolti i bug che rendono impossibile il suo utilizzo. In questo caso l'unica cosa che possiamo fare è rendere la schermata assenze una "funzionalità instabile" e farla visualizzare dal registro web.


> Detto questo torno a lamentarmi sul fatto delle notifiche che non è che arrivano con 1 ora di ritardo, magari fosse così , invece no ,delle volte non arrivano proprio o arrivano dopo 3/4 ore .Come è possibile che l'app del registro opensource LAMPSchool faceva comparire la notifica nello stesso momento in cui si pubblicava qualcosa?

Abbiamo già spiegato, nella sua precedente segnalazione di questo problema, il motivo dei ritardi (#178): 

"_I ritardi nelle notifiche sono dovuti sia per motivi di risparmio della batteria, infatti l'app controlla più o meno ogni 2 ore se ci sono novità, sia per come funziona l'app, infatti non essendoci un [API ](https://it.wikipedia.org/wiki/Application_programming_interface) del registro non si può ricevere un evento, come ad esempio la pubblicazione di un voto, in modo istantaneo._"
La preghiamo di non chiedere più volte le stesse cose a cui abbiamo già risposto.

Vorrei aggiungere anche che, il registro LAMPschool, giua@school e le loro app, sono ormai due registri ben diversi (descritto anche nella [documentazione di giua@school](https://iisgiua.github.io/giuaschool-docs/info.html)) e quindi non è possibile metterli a confronto con "lampschool lo faceva meglio", la cui frase potrebbe essere presa come un insulto verso chi impiega il proprio tempo a titolo gratuito per sviluppare l'app o per chi sviluppa il registro.

> Inoltre l'unica notifica che da dopo 3/4 ore è solo in merito alle valutazioni ,mentre ,per quanto riguarda le circolari ,i compiti ,programmazione delle verifiche non dà niente.

Controlli di aver seguito _tutte_ le istruzioni presenti nella schermata d'introduzione dell'app (accesibile da Impostazioni >  Rivedi Intro) e controllare le notifiche attivate dalla gestione notifiche (accesibile da Impostazioni > Gestione notifiche)
