### ISSUE TITLE
Supporto completo per istituti diversi

### ISSUE THREAD

**Issue by sempliciniluigi89** [Giua-app/Giua-App#79]
Buongiorno ,dal momento che troviamo difficoltà in quanto non sappiamo accedere direttamente con l'account google per studenti/genitori ,sarebbe possibile fare come LAMPSCHOOL? Ossia inserire il link del proprio registro e poi eventuali username e password e accedere direttamente ?Grazie mille

**Comment by HiemSword** [comment]
In questo momento l'app supporta solo parzialmente istituti diversi dal Giua, ma le illustrerò comunque i passaggi da fare.
Nell’ultima versione dell’app, andare su Impostazioni e attivare l’impostazione “Modalità di debug”, una volta attivata comparirà una nuova sezione nelle Impostazioni. Da li basta premere su “Imposta l’url del sito” e inserire l’URL del registro a cui si vuole accedere (è consigliato disattivare la modalità di debug dopo aver inserito l’URL)
Purtroppo essendo studenti impegnati ognuno nei propri studi e non avendo supporto dal nostro istituto non possiamo garantire il completo funzionamento dell’app in altri istituti

**Comment by sempliciniluigi89** [comment]
Grazie mille ,ora provo e le faccio sapere subito ,va bene?

**Comment by sempliciniluigi89** [comment]
Allora ho provato con le credenziali genitore a fare come da voi indicato ,ma quando inerisco la username e la password mi dice: è stato riscontrato qualche problema sconosciuto

**Comment by HiemSword** [comment]
Probabilmente l'app non riesce a trovare i campi di login della pagina, potrebbe mandare una foto dei LogDog (accesibili da Impostazioni > Debug > Mostra LogDog) ? Specialmente gli errori (colorati in rosso), in questo caso dovrebbe cercare una scritta simile a "Errore sconosciuto - " più il nome dell'errore

**Comment by sempliciniluigi89** [comment]
Certo certo, allego tutto qua sotto 


https://user-images.githubusercontent.com/93823125/147385862-9f61bffc-58f2-4627-9790-ad9129592e51.jpg

https://user-images.githubusercontent.com/93823125/147385867-3ab35193-512b-4029-b0e2-26552003558c.jpg

https://user-images.githubusercontent.com/93823125/147385868-762fedbb-e607-4989-82f0-759b4787b189.jpg

https://user-images.githubusercontent.com/93823125/147385869-23a1d3f6-de79-434c-af24-6e0ab7fa1b50.jpg

**Comment by sempliciniluigi89** [comment]
Foto allegate ,speriamo si possa risolvere il tutto il più presto possibile

**Comment by Franck1421** [comment]
Ci dispiace ma sicuramente risolveremo questo errore tra un bel po' di tempo dato che, come specificato da @HiemSword, siamo studenti impegnati ognuno nei propri studi e riusciamo a malapena a trovare il tempo per proseguire e far funzionare l'app nel nostro Istituto.

**Comment by sempliciniluigi89** [comment]
Va bene ,mi dispiace tantissimo ,ma non fa niente.Posso anche aspettare ,ma
vorrei che un giorno tutto funzionasse senza alcun tipo di problema,è un
progetto meraviglioso.Credo fortemente nella vostra forza,determinazione e
spirito di iniziativa.Grazie mille lo stesso



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
25/12/21,
16:05:55

Il giorno sab 25 dic 2021 alle ore 15:58 Franck1421 <
***@***.***> ha scritto:

**Comment by HiemSword** [comment]
Nell'ultima versione (0.6.3) è stato risolto questo bug, in più ora possibile impostare l'url del registro senza abilitare la modalità debug e il nome della scuola a cui si sta accedendo verrà mostrato nella pagina di login.
