### ISSUE TITLE
Agenda e notifiche agenda semi funzionanti

### ISSUE THREAD

**Issue by Franck1421** [Giua-app/Giua-App#81]

**Comment by HiemSword** [comment]
Per ora ho limitato le funzionalità dell'agenda con il commit https://github.com/Giua-app/giua-app.github.io/commit/a49d4fa2ec07b85b405963cd88f6649d3f38f581

**Comment by Franck1421** [comment]
Risolto in commit https://github.com/Giua-app/Giua-App/commit/71ef35377ecd1988caf4e706df2062b90c4db921
