### ISSUE TITLE
Impostazione url del sito non funziona

### ISSUE THREAD

**Issue by trinko** [Giua-app/Giua-App#83]
Sto cercando di testare l'app, ma quando imposto l'url del sito con l'indirizzo del mio server locale, sembra che l'impostazione non sia memorizzata.
Ogni tentativo di login, infatti, non arriva al server locale che ho impostato. Il LogDog conferma che continua a tentare di accedere a registro.giua.edu.it.

Sto utilizzando la versione 0.6.2-stable

**Comment by HiemSword** [comment]
Posso chiederle se quando riprova a riapre il dialogo dell'url esce l'url impostato o registro.giua.edu.it? Se non esce l'url impostato, è probabile che non sia un url valido (es. http://example.com)

**Comment by sempliciniluigi89** [comment]
@trinko Riscontro lo stesso problema

**Comment by trinko** [comment]
> Posso chiederle se quando riprova a riapre il dialogo dell'url esce l'url impostato o registro.giua.edu.it? Se non esce l'url impostato, è probabile che non sia un url valido (es. http://example.com)

Esce sempre registro.giua.edu.it. Ma l'url impostato è valido, solo che è un indirizzo IP di rete locale (https://192.168.1.180/...)

**Comment by Franck1421** [comment]
Risolto in commit https://github.com/Giua-app/Giua-App/commit/292992931246f05f7971880846816227b697a4c5
Purtroppo il fix sarà accessibile solo alla prossima release che non si sa ancora quando sarà disponibile. Alternativamente si può provare ad installare l'app da https://github.com/Giua-app/Giua-App/actions appena sarà possibile, ovvero quando verrà visualizzata una spunta verde tra le ultime build. Avviso però che le versioni che si trovano nelle Actions possono essere molto instabili pertanto chiediamo di non segnalare nemmeno eventuali bug o problemi qui tra le issues.

**Comment by HiemSword** [comment]
Fix incluso nell'ultima versione dell'app ([0.6.3](https://github.com/Giua-app/Giua-App/releases/tag/0.6.3))
