### ISSUE TITLE
Impostazione url non funziona

### ISSUE THREAD

**Issue by manuelbarberi** [Giua-app/Giua-App#85]
Salve, quando vado ad inserire l’url dominio.altervista.org/public porta url errato

**Comment by Franck1421** [comment]
Si al momento l'app accetta solo URL del tipo http(s)://example.com quindi provi con http://dominio.altervista.org

**Comment by manuelbarberi** [comment]
Già provato mi dà errore… posso mandare la foto?

**Comment by Franck1421** [comment]
Certo

**Comment by manuelbarberi** [comment]
![image](https://user-images.githubusercontent.com/96074009/148642900-e3bdf145-16c7-4529-95a5-930d516b1290.jpg)

**Comment by manuelbarberi** [comment]
Foto allegata

**Comment by Franck1421** [comment]
Ma per entrare nel registro dal browser l'URL che utilizza è del tipo http://dominio.altervista.org oppure http://dominio.altervista.org/public?

**Comment by manuelbarberi** [comment]
Il secondo /public

**Comment by Franck1421** [comment]
Al momento l'app non supporta questo tipo di URL, lo aggiungeremo nella prossima release.

**Comment by manuelbarberi** [comment]
Quando dovrebbe uscire orientativamente ?

**Comment by Franck1421** [comment]
Impossibile stabilirlo attualmente in quanto prima di fare la release dovremo implementare anche altre funzionalità e questo richiede del tempo e dato che siamo degli studenti siamo impegnati anche in altre attività. Posso dirle che solitamente (ma non necessariamente) facciamo release 1 volta al mese.

**Comment by Franck1421** [comment]
La rimando alla Issue https://github.com/Giua-app/Giua-App/issues/83
