### ISSUE TITLE
Download circolari non funziona con url del registro personalizzato

### ISSUE THREAD

**Issue by sempliciniluigi89** [Giua-app/Giua-App#91]
Buongiorno ,stiamo riscontrando numerose difficoltà nell'area bacheca circolari ,in quanto quando si vuole scaricare la circolare esce sempre il seguente messaggio di errore che non permetta la visualizzazione della stessa:  E' STATO INCONTRATO UN ERRORE DI RETE DURANTE IL DOWNLOAD:RIPROVA

**Comment by HiemSword** [comment]
Bug confermato, si verifica solo se si usa un registro diverso. Verrà risolto nella prossima release

**Comment by sempliciniluigi89** [comment]
Speriamo il più presto possibile in modo da permettere ai genitori/alunni di leggere le circolari

**Comment by sempliciniluigi89** [comment]
Stesso problema si verifica nella lettura degli avvisi e credo anche
documenti

Il Dom 16 Gen 2022, 17:20 Hiem ***@***.***> ha scritto:

**Comment by sempliciniluigi89** [comment]
Sarebbe possibile far vedere i dati anagrafici dello studente e la classe
oltre che la possibilità di modificare la password direttamente dall'app ?
Sarebbe possibile per i genitori con più figli implementare l'utilizzo di
più account?

Il Dom 16 Gen 2022, 22:11 Luigi Semplicini ***@***.***> ha
scritto:

**Comment by sempliciniluigi89** [comment]
Stesso problema si presenta quando si clicca sul calendario/agenda per
vedere le verifiche fissate

Il Dom 16 Gen 2022, 22:14 Luigi Semplicini ***@***.***> ha
scritto:

**Comment by sempliciniluigi89** [comment]
Non capisco il motivo per il quale riporta comunque la media nella grafica
dell'andamento anche se il voto di fatto non fa media

Il Lun 17 Gen 2022, 00:13 Luigi Semplicini ***@***.***> ha
scritto:

**Comment by HiemSword** [comment]
> Sarebbe possibile far vedere i dati anagrafici dello studente e la classe oltre che la possibilità di modificare la password direttamente dall'app ? Sarebbe possibile per i genitori con più figli implementare l'utilizzo di più account? 

Si, è possibile e verranno implementate tutti e tre in futuro ma, come sempre, non possiamo garantirle ne quando verranno implementate ne quando verranno rilasciate al pubblico.

**Comment by Franck1421** [comment]
Risolto, sarà disponibile nella prossima versione
