### ISSUE TITLE
Layout voti

### ISSUE THREAD

**Issue by sempliciniluigi89** [Giua-app/Giua-App#92]
Buongiorno,per quanto riguarda la sezione voti si potrebbe cambiare layout facendola più moderna e simile alle altre app ex
Registro Argo/classeviva ,inoltre si potrebbe dividere argomenti e compiti in due sezioni ben distinte?Inoltre si potrebbe vedere la firma del docente nella sezione attività svolta?

**Comment by HiemSword** [comment]
Per quanto riguarda la firma del docente, purtroppo non possiamo farla vedere perchè anche nella pagina web del registro non è presente per gli account studenti e genitori. Le ricordo che **le funzionalità dell'app dipendono dal registro elettronico** e da ciò che gli account possono vedere quindi non possiamo implementare funzionalità inesistenti nel registro.

Per quanto riguarda invece il layout della sezione voti, le ricordo che siamo 3 studenti che si sono messi a creare quest'app di propria spontanea volontà senza supporto ne dal nostro istituto ne da terzi usando il nostro stesso tempo libero, purtroppo quindi non abbiamo tempo per rimodernizzare l'interfaccia tranne che per piccole migliorie. Se il nostro istituto supporterà il progetto e in molti chiederanno la rimodernizzzione dell'interfaccia allora ci lavoreremo, per ora l'interfaccia attuale, secondo noi, è più che sufficiente.
