### ISSUE TITLE
Lo scraper taglia la frase in presenza di ": "

### ISSUE THREAD

**Issue by sempliciniluigi89** [Giua-app/Giua-App#94]
Buongiorno, ho notato che l'app riporta un numero limitato nelle parole per quanto riguarda  la descrizione del voto e forse anche il commento da parte del docente per il voto.

**Comment by HiemSword** [comment]
In realtà il testo degli argomenti e quello dei giudizi può scorrere per far vedere il resto del testo, basta muovere il dito dal basso verso l'altro.

**Comment by sempliciniluigi89** [comment]
Purtroppo no,quando clicco sul voto per vedere i dettagli, per quanto
riguarda gli argomenti si ferma su un numero limitato di parole ,nonostante
sposti o trascini in basso

Il Mar 18 Gen 2022, 22:27 Hiem ***@***.***> ha scritto:

**Comment by Franck1421** [comment]
Mandi uno screenshot

**Comment by sempliciniluigi89** [comment]
L'argomento completo dovrebbe essere:Risposta alla domanda Cos'è la
Religione?

Il Mar 18 Gen 2022, 22:44 Franck1421 ***@***.***> ha scritto:

**Comment by sempliciniluigi89** [comment]
Poi non capisco perché nella grafica dell'andamento scolastico viene
calcolato anche il voto che non fa media

Il Mar 18 Gen 2022, 22:50 Luigi Semplicini ***@***.***> ha
scritto:

**Comment by sempliciniluigi89** [comment]
Le mando lo screen sulla mail

**Comment by sempliciniluigi89** [comment]
Mi potrebbe fornire la sua mail?

**Comment by Franck1421** [comment]
La prego di parlare solamente dell'argomento scritto nel titolo e se ci sono altri problemi che non riguardano tale argomento dovrebbe aprire un'altra issue per discuterne là. Ad ogni modo è un bug di cui siamo a conoscenza.

**Comment by Franck1421** [comment]
Le immagini si possono caricare anche qui su GitHub però se trova problemi può mandarla a frank21thegamer@gmail.com

**Comment by sempliciniluigi89** [comment]
Immagine inviata sulla mail

**Comment by Franck1421** [comment]
Si ricevuta, prima di segnalarlo come bug le chiedo: ha provato a trascinare la scritta dal basso verso l'alto (probabilmente è nascosto in basso e stiamo già lavorando ad un modo per renderlo più chiaro)? Può ricontrollare dal registro elettronico online che l' argomento del voto corrisponde a quello voluto?

**Comment by sempliciniluigi89** [comment]
È proprio quello che ho fatto quasi tutto il giorno,ma niente da
fare.Addirittura ho controllato sul registro web (lato genitore) e l'altra
parte risulta ,quindi il problema è dovuta all'app

Il Mar 18 Gen 2022, 23:18 Franck1421 ***@***.***> ha scritto:

**Comment by Franck1421** [comment]
Potrebbe inviare lo screenshot della argomento del voto preso dal registro online?

**Comment by sempliciniluigi89** [comment]
Certo

Il Mar 18 Gen 2022, 23:29 Franck1421 ***@***.***> ha scritto:

**Comment by Franck1421** [comment]
Risolto in https://github.com/Giua-app/Giua-App/commit/221ded6e213b490d68fe0c6749a28491152ead94
