### ISSUE TITLE
Grafica innovativa e arricchita app giua

### ISSUE THREAD

**Issue by sempliciniluigi89** [Giua-app/Giua-App#95]
Buonasera, allego  alcune foto di come potrebbe essere arricchita la grafica dell'app giua 

https://user-images.githubusercontent.com/93823125/150004616-037c04dd-fd4b-4296-9c1e-d8b9699ab6e0.jpg
https://user-images.githubusercontent.com/93823125/150004631-382b9819-ceec-438e-a249-58a3c2719141.jpg
https://user-images.githubusercontent.com/93823125/150004637-8e9b0e81-4c15-406f-9e74-0268a548d7db.jpg
https://user-images.githubusercontent.com/93823125/150004638-973fe441-485e-4a25-816d-5ef420bcb002.jpg
![unnamed-5](https://user-images.githubusercontent.com/93823125/150004641-24979f1e-315d-4610-97c3-006e5e8a4e31.jpg
https://user-images.githubusercontent.com/93823125/150004646-3e3d5126-a2a6-4a73-bf2d-618e3368de9b.jpg

**Comment by HiemSword** [comment]
Grazie, terremo a mente il materiale che ci ha inviato ma, come ho scritto su #92, inizieremo ad arrichire la grafica dell'app quando avremmo più tempo per lavorarci e quando il nostro istituto ci supporterà in questo progetto
